// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Meeting struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	StartTime   int    `json:"startTime"`
}

type NewTodo struct {
	ID          int    `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	StartTime   int    `json:"startTime"`
}

type Todo struct {
	ID      int      `json:"id"`
	Meeting *Meeting `json:"meeting"`
}
